version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/CD-CP
    fileExistsBehavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180

  Install:
    - location: scripts/install.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
